version: '3.8'
services:
  app:
    container_name: limbic-chatbot_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: Password!123
      DB_NAME: limbic-chatbot
  db:
    container_name: limbic-chatbot_db
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
volumes:
  db-data:
